#!/bin/bash
API_KEY="$ELEVENLABS_API_KEY"
ERIC="9T9vSqRrPPxIs5wpyZfK"
CHRIS="iP95p4xoKVk53GoZ742B"

render() {
  local file="$1" voice_id="$2" text="$3"
  if [ -f "$file" ]; then echo "SKIP $file"; return; fi
  echo "Rendering $file..."
  local body="{\"text\":$(python3 -c "import json,sys;print(json.dumps(sys.argv[1]))" "$text"),\"model_id\":\"eleven_multilingual_v2\",\"voice_settings\":{\"stability\":0.5,\"similarity_boost\":0.75}}"
  local status
  status=$(curl -s -o "$file" -w "%{http_code}" \
    "https://api.elevenlabs.io/v1/text-to-speech/${voice_id}" \
    -H "xi-api-key: ${API_KEY}" \
    -H "Content-Type: application/json" \
    -d "$body")
  if [ "$status" = "200" ]; then
    echo "OK $file ($(stat -c%s "$file") bytes)"
  else
    echo "FAIL $file (HTTP $status)"
    cat "$file" 2>/dev/null; echo
    rm -f "$file"
  fi
  sleep 1
}

# ROOFERS - Eric
render roofers_v1_eric.mp3 "$ERIC" "Hey there, this is Jason. I was doing some research on roofing companies in the DFW area and came across yours. Most roofing owners I talk to are either slammed one month and slow the next — never really consistent, you know? I help fix that and can prove we'll get you 25% more jobs on your schedule in the next 45 days. If you want a free breakdown of how to fill your calendar year-round, give me a call back or shoot me a quick text. I'll put something together specifically for your business, completely free. Talk to you soon!"
render roofers_v2_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just looking into roofing companies in the DFW area and found yours. I just helped another roofing company increase their monthly jobs by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render roofers_v3_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just doing some research on roofing companies in the DFW area and came across yours. I recently worked with another roofer — they were pretty much relying only on referrals, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# GC - Eric
render general_contractors_v1_eric.mp3 "$ERIC" "Hey there, this is Jason. I was doing some research on general contractors in the DFW area and came across yours. Most GC owners I talk to have the same issue — you're juggling bids, managing crews, and somehow still chasing the next job at the same time. Never really consistent, you know? I help fix that and can prove we'll get you 25% more jobs lined up in the next 45 days. If you want a free breakdown of how to keep your pipeline full year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render general_contractors_v2_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just looking into general contractors in the DFW area and found yours. I just helped another GC increase their monthly jobs by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render general_contractors_v3_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just doing some research on general contractors in the DFW area and came across yours. I recently worked with another contractor — they were pretty much relying only on word of mouth and repeat clients, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# ELECTRICIANS - Eric
render electricians_v1_eric.mp3 "$ERIC" "Hey there, this is Jason. I was doing some research on electrical companies in the DFW area and came across yours. Most electricians I talk to are either booked out two weeks or sitting around waiting for the phone to ring — never really consistent, you know? I help fix that and can prove we'll get you 25% more service calls in the next 45 days. If you want a free breakdown of how to keep your schedule full year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render electricians_v2_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just looking into electrical companies in the DFW area and found yours. I just helped another electrician increase their monthly service calls by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render electricians_v3_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just doing some research on electrical companies in the DFW area and came across yours. I recently worked with another electrician — they were pretty much relying only on referrals and Angi leads, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# FENCE - Eric
render fence_v1_eric.mp3 "$ERIC" "Hey there, this is Jason. I was doing some research on fence companies in the DFW area and came across yours. Most fence company owners I talk to have the same problem — spring hits and you're drowning in estimates, then it slows down and you're chasing work. Never really consistent, you know? I help fix that and can prove we'll get you 25% more jobs on your schedule in the next 45 days. If you want a free breakdown of how to keep your crews busy year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render fence_v2_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just looking into fence companies in the DFW area and found yours. I just helped another fence company increase their monthly jobs by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render fence_v3_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just doing some research on fence companies in the DFW area and came across yours. I recently worked with another fence builder — they were pretty much relying only on yard signs and word of mouth, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# GARAGE DOOR - Eric
render garage_door_v1_eric.mp3 "$ERIC" "Hey there, this is Jason. I was doing some research on garage door companies in the DFW area and came across yours. Most garage door guys I talk to are either running on emergency calls all week or wondering where the next job's coming from — never really consistent, you know? I help fix that and can prove we'll get you 25% more service calls in the next 45 days. If you want a free breakdown of how to keep your phone ringing year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render garage_door_v2_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just looking into garage door companies in the DFW area and found yours. I just helped another garage door company increase their monthly calls by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render garage_door_v3_eric.mp3 "$ERIC" "Hey there, this is Jason. I was just doing some research on garage door companies in the DFW area and came across yours. I recently worked with another garage door guy — they were pretty much relying only on Google ads and HomeAdvisor, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# CONCRETE - Chris
render concrete_v1_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was doing some research on concrete contractors in the DFW area and came across yours. Most concrete guys I talk to have the same issue — you're busy as hell when weather's good, then it dries up and you're scrambling for bids. Never really consistent, you know? I help fix that and can prove we'll get you 25% more jobs on your schedule in the next 45 days. If you want a free breakdown of how to keep your crews pouring year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render concrete_v2_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just looking into concrete contractors in the DFW area and found yours. I just helped another concrete company increase their monthly jobs by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render concrete_v3_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just doing some research on concrete contractors in the DFW area and came across yours. I recently worked with another concrete guy — they were pretty much relying only on referrals and repeat customers, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# HVAC - Chris
render hvac_v1_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was doing some research on HVAC companies in the DFW area and came across yours. Most HVAC owners I talk to are either slammed during summer and winter, then crickets in between — never really consistent, you know? I help fix that and can prove we'll get you 25% more service calls in the next 45 days. If you want a free breakdown of how to fill your schedule year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render hvac_v2_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just looking into HVAC companies in the DFW area and found yours. I just helped another HVAC company increase their monthly service calls by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render hvac_v3_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just doing some research on HVAC companies in the DFW area and came across yours. I recently worked with another HVAC company — they were pretty much relying only on referrals and repeat customers, so we got them to about 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# LANDSCAPING - Chris
render landscaping_v1_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was doing some research on landscaping companies in the DFW area and came across yours. Most landscaping owners I talk to have the same thing going on — spring and summer you're turning down work, then winter hits and the phone goes quiet. Never really consistent, you know? I help fix that and can prove we'll get you 25% more jobs on your schedule in the next 45 days. If you want a free breakdown of how to keep your crews busy year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render landscaping_v2_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just looking into landscaping companies in the DFW area and found yours. I just helped another landscaping company increase their monthly jobs by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render landscaping_v3_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just doing some research on landscaping companies in the DFW area and came across yours. I recently worked with another landscaper — they were pretty much relying only on yard signs and Nextdoor posts, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

# PLUMBERS - Chris
render plumbers_v1_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was doing some research on plumbing companies in the DFW area and came across yours. Most plumbing company owners I talk to are either running nonstop on emergency calls or wondering where the next big job's coming from — never really consistent, you know? I help fix that and can prove we'll get you 25% more service calls in the next 45 days. If you want a free breakdown of how to keep your schedule full year-round, give me a call back or shoot me a quick text. Completely free. Talk to you soon!"
render plumbers_v2_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just looking into plumbing companies in the DFW area and found yours. I just helped another plumber increase their monthly service calls by about 25% in like 45 days... without them lifting a finger. So if you want me to walk you through how we did it and build something custom for your business at no cost, just give me a call back or shoot me a text for more info. Talk to you soon!"
render plumbers_v3_chris.mp3 "$CHRIS" "Hey there, this is Jason. I was just doing some research on plumbing companies in the DFW area and came across yours. I recently worked with another plumber — they were pretty much relying only on HomeAdvisor and repeat customers, so we got them to like 25% more jobs every month. And it's completely on autopilot now. They don't even think about it. So anyway, if you want me to walk you through exactly how we pulled that off, I can put together something custom for your business, no charge. Just give me a call back at this number. Talk to you soon!"

echo ""
echo "=== COMPLETE ==="
echo "Files rendered: $(ls *.mp3 2>/dev/null | wc -l) / 27"
ls -lhS *.mp3 2>/dev/null
